name: CI - PHP Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:10.11
        env:
          MYSQL_ROOT_PASSWORD: foro_pass
          MYSQL_DATABASE: foro
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mysqli
          coverage: none

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer

      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit

      - name: Wait for database
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -pforo_pass --silent; do
            echo "Esperando a MariaDB..."
            sleep 2
          done
          echo "MariaDB lista"

      - name: Base de Datos
        run: mysql -h 127.0.0.1 -uroot -pforo_pass foro < BBDD/script_creacion.sql

      - name: Extaraer par치metros y probar conexi칩n
        run: |
          ls 
          DB_USER=$(grep DB_USER ../BBDD/config/bbdd.php | head -1 | cut -d"'" -f2)
          DB_PASS=$(grep DB_PASS ../BBDD/config/bbdd.php | head -1 | cut -d"'" -f2)
          DB_NAME=$(grep DB_NAME ../BBDD/config/bbdd.php | head -1 | cut -d"'" -f2)

          mysql -h 127.0.0.1 -u"$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "exit"

          if [ $? -ne 0 ]; then
            echo "Fallo en la conexi칩n"
            exit 1
          else
            echo "Conexi칩n exitosa"
          fi

      - name: Run Tests
        run: ./vendor/bin/phpunit tests
